services:
  db:
    image: mysql:8.0
    container_name: mysql-bookdb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Initialize the DB on first container start by placing SQL here
      - ./backend/sqlDumps/dump-bookdb-202506172110.sql:/docker-entrypoint-initdb.d/dump-bookdb-202506172110.sql:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bd-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=mysql+pymysql://appuser:apppassword@db:3306/bookdb
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bd-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm","run","dev","--","--host"]
    environment:
      - CHOKIDAR_USEPOLLING=true   # optional, only if watch doesn't detect changes
    depends_on:
      - backend

volumes:
  db_data: